apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-app-demo-k8s-secret
  name: nodejs-app-demo--k8s-secret-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app-demo-k8s-secret
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app-demo-k8s-secret
      name: nodejs-app-demo-k8s-secret
    spec:
      imagePullSecrets:
        - name: sample-regcred
      containers:
        - image: sdubey321/sdubey321-private-repo:1.1.0
          name: nodejs-app-demo-k8s-secret
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nodejs-app-demo-config-configmap2
          env:
            - name: DB_PASSWORD_NODE_DEMO
              valueFrom:
                secretKeyRef:
                  key: password
                  name: nodejs-app-demo-k8s-secret
