apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app-demo-configmap-pod
  labels:
    app: nodejs-app-demo-configmap
spec:
  containers:
    - name: nodejs-app-demo-configmap
      image: sdubey321/nodejs-app-demo-configmap:1.0.0
      ports:
        - containerPort: 3000
      env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT_FROM_CONFIGMAP
              name: nodejs-app-demo-config-configmap
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              key: APP_NAME_FORM_CONFIGMAP
              name: nodejs-app-demo-config-configmap
        - name: CONFIGMAP1
          valueFrom:
            configMapKeyRef:
              key: CONFIGMAP1_FROM_CONFIGMAP
              name: nodejs-app-demo-config-configmap
        - name: CONFIGMAP2
          valueFrom:
            configMapKeyRef:
              key: CONFIGMAP2_FROM_CONFIGMAP
              name: nodejs-app-demo-config-configmap
